CorumSource-master/Corum.AdminUI/Controllers/PublicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorumAdminUI.Controllers
{
    [AllowAnonymous]
    public class PublicController : CorumBaseController
    {                
        [HttpGet]
        [OutputCache(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult OperationSuccess(long Id)
        {
            return View(Id);
        }
        
        [HttpGet]
        [OutputCache(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult Entry()
        {
            var model = context.getAvailableOrderTypes(null, null).Where(x=>x.IsActive==true).ToList();
            return View(model);
        }

        [HttpGet]
        [OutputCache(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult NewOrderPublicEntry(int OrderTypeId)
        {
            return RedirectToAction("NewOrder", "Orders", new { OrderTypeId, PublicEntry = true });
        }
    }
}

CorumSource-master/Corum.AdminUI/Views/Public/Entry.cshtml
@model  List<Corum.Models.ViewModels.Orders.OrderTypeViewModel>

@{    
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 main">
        <h4>Выберите тип транспортной заявки для добавления</h4>   
        <div style="font-size: 13px;">
            <div class="grid-mvc">
                <div class="grid-wrap">
                    <table class="table table-striped table-bordered no-footer sort-table-header">
                        <thead>
                        <tr>
                            <th class="grid-header centered_column">Наименование типа</th>                            
                            <th class="grid-header"></th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach (var type in Model)
                            {
                                <tr class="odd gradeX">
                                    <td class="">
                                        <div style="float: left">
                                            @type.TypeName
                                        </div>
                                    </td>                                     
                                    <td class="centered_column">
                                        @Html.ActionLink("Добавить", "NewOrderPublicEntry", "Public",  new { OrderTypeId = type.Id }, new { @class = "btn btn-success" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
          </div>            
        </div>
    </div>
</div>

CorumSource-master/Corum.AdminUI/Views/Public/OperationSuccess.cshtml
@model  long

@{    
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row centered_column">        
        <h4>Ваша заявка № @Model.ToString() успешно принята</h4>           
    </div>
    <div>
        @Html.ActionLink("Добавить еще одну заявку", "Entry", "Public", null, new { @class = "btn btn-success", @style = "margin-left:20px;" })
    </div>
</div>